name: Build

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-use-ruby-${{matrix.ruby}}
        restore-keys: |
          bundle-use-ruby-${{matrix.ruby}}
    - name: Bundle install...
      run: |
        bundle install
    - run: bundle exec rake
